### ISSUE TITLE
Update the database

### ISSUE THREAD

**Issue by sochka** [Wapweb/api.rozklad.org.ua#10]
The new cemester is coming, please update the DB.

**Comment by Wapweb** [comment]
fixed

**Comment by sashasochka** [comment]
@Wapweb , hi, could you please update the DB at least once per one-three days during the next two weeks? I'm going to release the new version of kpiexport tool, and people might be frustrated if theirs group is not there. Thanks a lot for a great backend.

**Comment by Wapweb** [comment]
@sochka Hi. i'll try to do something)
