### ISSUE TITLE
Get list of all groups (without limits)

### ISSUE THREAD

**Issue by sochka** [Wapweb/api.rozklad.org.ua#11]
Hi, by default you output only 100 groups with this api request. `http://api.rozklad.org.ua/v2/groups/` But adding filter limit doesn't seem to help. I guess that's a bug. `http://api.rozklad.org.ua/v2/groups/?filter={%22limit%22:10000}` (this still outputs 100 groups).

**Comment by Wapweb** [comment]
Hi. It is not a bug. The maximum value of limit filter is 100. See https://github.com/Wapweb/api.rozklad.org.ua/blob/master/application/models/GroupModel.php#L68

**Comment by Wapweb** [comment]
Get all groups http://api.rozklad.org.ua/v2/groups/?filter={'showAll':true}
https://github.com/Wapweb/api.rozklad.org.ua/commit/50bf78319c9730596987c41de64345b4eb298a80

**Comment by Wapweb** [comment]
https://github.com/Wapweb/api.rozklad.org.ua/commit/50bf78319c9730596987c41de64345b4eb298a80
